### PR TITLE
Fix bug: serviceName not being set in locals

### LINKED ISSUE #71: Rename NHSPrototypeKit.expressMiddleware.all() to NHSPrototypeKit.expressMiddleware.configure()
A suggestion from @colinrotherham - might be clearer?

See https://github.com/nhsuk/nhsuk-prototype-kit-package/pull/70#discussion_r2550329473

### PR DESCRIPTION
**Pull request by frankieroberto**
`serviceName` needs to be set in locals before autoRoutes and other middleware that might render the page.

Accidental bug introduced in #134.

Also fixes #71

### CODE REVIEW

File: lib/middleware/index.js [hunk 1]
```diff
@@ -132,7 +136,6 @@ export function all(options) {
   app.use(renderPageNotFound, renderErrorPage)
 
   return function (req, res, next) {
-    res.locals.serviceName = serviceName
```
Comment (colinrotherham) [inline lib/middleware/index.js]: There's no middleware anymore

So we don't need `app.use()` around the `.all()` call

Comment (frankieroberto) [reply lib/middleware/index.js]: am confused, sorry. The `serviceName` currently isn't being set in locals in `main`.

Comment (colinrotherham) [reply lib/middleware/index.js]: The now-empty middleware function can entirely go

```patch
    // Page not found - this must come last
    app.use(renderPageNotFound, renderErrorPage)
- 
-   return function (req, res, next) {
-     res.locals.serviceName = serviceName
-     next()
-   }
```

Comment (frankieroberto) [reply lib/middleware/index.js]: Ahh I get you now. Ok this is done.
